In [1]:
print("testing")

testing

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./combined_df.csv')

In [4]:
df.head()

,query,emotion,response
0,I've been feeling overwhelmed and helpless lat...,fear,I can see how challenging it must be for you t...
1,The weight of stress feels unbearable. It affe...,sad,Stress can indeed be overwhelming and impact v...
2,I've been feeling really down lately and it's ...,sad,Managing depression and improving your overall...
3,I've been feeling overwhelmed by the constant ...,surprise,Your life has been filled with significant cha...
4,"Hello, I'm Emma and I'm here to discuss my anx...",fear,Flying can definitely be a challenging experie...

In [19]:
df = pd.read_csv('./knowledge_base.csv')

In [20]:
df.head(25)

,query,emotion,response,category_1,category_2
0,I've been feeling overwhelmed and helpless lat...,fear,I can see how challenging it must be for you t...,Work & Career Stress,NaN
1,The weight of stress feels unbearable. It affe...,sad,Stress can indeed be overwhelming and impact v...,Work & Career Stress,NaN
2,I've been feeling really down lately and it's ...,sad,Managing depression and improving your overall...,Depression & Mood,Grief & Loss
3,I've been feeling overwhelmed by the constant ...,surprise,Your life has been filled with significant cha...,Life Transitions & Existential Crisis,Family Issues
4,"Hello, I'm Emma and I'm here to discuss my anx...",fear,Flying can definitely be a challenging experie...,Anxiety & Panic,Health & Medical Concerns
5,I've been attending this religious study group...,sad,Your journey towards self-expression is an imp...,Self-Esteem & Identity,NaN
6,(Deep breath) I remember that day clearly. [Na...,fear,I'm sorry to hear that your interaction with [...,Trauma & PTSD,NaN
7,I've been grappling with feelings of guilt and...,fear,"Your description of the situation is clear, an...",Self-Esteem & Identity,Family Issues
8,"Hi, counselor. Depression has left me feeling ...",sad,I appreciate you reaching out and sharing your...,Depression & Mood,Relationship Issues
9,I understand. I remember one question from the...,surprise,"Yes, that's a common perspective. A structured...",Positive Growth & Resilience,NaN
10,Human Sexuality\n\nMessage 9:\nI am struggling...,fear,Understanding and accepting your own sexuality...,Sexual Identity & Orientation,NaN
11,I am so angry. I feel like the arguments with ...,angry,"First off, it is great that you recognize that...",Anger & Conflict,Financial Stress
12,"Hey, therapist. Anxiety has been consuming my ...",fear,It sounds like you've been dealing with a lot ...,Anxiety & Panic,Social Skills & Relationships
13,I've been trying to access grief support servi...,sad,I can only imagine how disheartening it must b...,Grief & Loss,Depression & Mood
14,(pausing to gather thoughts) I've been dealing...,fear,I understand the gravity of your situation. It...,Work & Career Stress,NaN
15,I've been struggling with my mother's constipa...,fear,I can imagine how challenging it must be for y...,Health & Medical Concerns,Anxiety & Panic
16,That doesn't make sense,disgust,I'm very sorry. Let's try that again,General Mental Health,NaN
17,"I've attempted some of those things, like avoi...",fear,It's natural for progress to be inconsistent w...,Sleep & Fatigue,Anxiety & Panic
18,"Throughout my life, I have struggled with main...",sad,It can be incredibly challenging to maintain a...,Self-Esteem & Identity,Depression & Mood
19,"My days are clouded by a heavy sadness, robbin...",sad,It sounds like you are dealing with a heavy sa...,Depression & Mood,Self-Esteem & Identity
20,Parenting)\nMy goal through this counseling s...,angry,To improve your parenting skills and foster a ...,General Mental Health,Relationship Issues
21,"Sometimes, I find myself caught in a cycle of ...",fear,It can be challenging when negative thoughts a...,OCD & Intrusive Thoughts,Depression & Mood
22,Depression has affected my daily life in vario...,sad,It can be really tough when depression starts ...,Depression & Mood,Body Image & Eating Disorders
23,"I've tried reaching out to support groups, but...",sad,I can imagine how isolating it feels to search...,Family Issues,Depression & Mood
24,I've been struggling to cope with the loss of ...,fear,I can empathize with your feelings of helpless...,Grief & Loss,Loneliness & Social Isolation

In [21]:
df["query"][5]

"I've been attending this religious study group, and it's given me a chance to express my thoughts freely without fear of judgment or reprisal. Even though I'm the only one in the room who holds these views, I find it helpful to practice articulating my ideas. In my childhood home and with my relatives, I was always careful not to stray too far from the accepted beliefs. But deep down, I've always felt more comfortable with my natural inclinations. I'd like to work on asserting myself more in various situations, not just this one, so that I don't feel as awkward when I'm expressing my thoughts."